version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elecdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elec-net
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
      - .:/app:ro
    networks:
      - elec-net

volumes:
  postgres_data:

networks:
  elec-net:
